"""
Generated by Statechart compiler by Glenn De Jonghe, Joeri Exelmans, Simon Van Mierlo, and Yentl Van Tendeloo (for the inspiration) and Sam Pieters (DEVS)

Model author: Simon Van Mierlo
Model name:   Timer (Eventloop Version)

"""

from sccd.runtime.DEVS_statecharts_core import *
from pypdevs.DEVS import *
from pypdevs.infinity import *
from pypdevs.simulator import *
from sccd.runtime.libs.ui import ui
from time import time

CANVAS_WIDTH = 800
CANVAS_HEIGHT = 550

# package "Timer (Eventloop Version)"

class MainAppInstance(RuntimeClassBase):
    def __init__(self, atomdevs):
        RuntimeClassBase.__init__(self, atomdevs)
        self.associations = {}
        
        self.semantics.big_step_maximality = StatechartSemantics.TakeMany
        self.semantics.internal_event_lifeline = StatechartSemantics.Queue
        self.semantics.input_event_lifeline = StatechartSemantics.FirstComboStep
        self.semantics.priority = StatechartSemantics.SourceParent
        self.semantics.concurrency = StatechartSemantics.Single
        
        # build Statechart structure
        self.build_statechart_structure()
        
        # user defined attributes
        self.window_id = None
        self.canvas_id = None
        self.clock_id = None
        self.actual_clock_id = None
        self.button_id = None
        
        # call user defined constructor
        MainAppInstance.user_defined_constructor(self)
        self.inports["field_ui"] = ('field_ui', len(atomdevs.instances))
    
    def user_defined_constructor(self):
        pass
    
    def user_defined_destructor(self):
        pass
    
    
    # builds Statechart structure
    def build_statechart_structure(self):
        
        # state <root>
        self.states[""] = State(0, "", self)
        
        # state /creating_window
        self.states["/creating_window"] = State(1, "/creating_window", self)
        self.states["/creating_window"].setEnter(self._creating_window_enter)
        
        # state /creating_canvas
        self.states["/creating_canvas"] = State(2, "/creating_canvas", self)
        self.states["/creating_canvas"].setEnter(self._creating_canvas_enter)
        
        # state /creating_clock_text
        self.states["/creating_clock_text"] = State(3, "/creating_clock_text", self)
        self.states["/creating_clock_text"].setEnter(self._creating_clock_text_enter)
        
        # state /creating_actual_clock_text
        self.states["/creating_actual_clock_text"] = State(4, "/creating_actual_clock_text", self)
        self.states["/creating_actual_clock_text"].setEnter(self._creating_actual_clock_text_enter)
        
        # state /creating_interrupt_button
        self.states["/creating_interrupt_button"] = State(5, "/creating_interrupt_button", self)
        self.states["/creating_interrupt_button"].setEnter(self._creating_interrupt_button_enter)
        
        # state /creating_resume_button
        self.states["/creating_resume_button"] = State(6, "/creating_resume_button", self)
        self.states["/creating_resume_button"].setEnter(self._creating_resume_button_enter)
        
        # state /running
        self.states["/running"] = State(7, "/running", self)
        self.states["/running"].setEnter(self._running_enter)
        self.states["/running"].setExit(self._running_exit)
        
        # state /interrupted
        self.states["/interrupted"] = State(8, "/interrupted", self)
        
        # add children
        self.states[""].addChild(self.states["/creating_window"])
        self.states[""].addChild(self.states["/creating_canvas"])
        self.states[""].addChild(self.states["/creating_clock_text"])
        self.states[""].addChild(self.states["/creating_actual_clock_text"])
        self.states[""].addChild(self.states["/creating_interrupt_button"])
        self.states[""].addChild(self.states["/creating_resume_button"])
        self.states[""].addChild(self.states["/running"])
        self.states[""].addChild(self.states["/interrupted"])
        self.states[""].fixTree()
        self.states[""].default_state = self.states["/creating_window"]
        
        # transition /creating_window
        _creating_window_0 = Transition(self, self.states["/creating_window"], [self.states["/creating_canvas"]])
        _creating_window_0.setAction(self._creating_window_0_exec)
        _creating_window_0.setTrigger(Event("window_created", None))
        self.states["/creating_window"].addTransition(_creating_window_0)
        
        # transition /creating_canvas
        _creating_canvas_0 = Transition(self, self.states["/creating_canvas"], [self.states["/creating_clock_text"]])
        _creating_canvas_0.setAction(self._creating_canvas_0_exec)
        _creating_canvas_0.setTrigger(Event("canvas_created", None))
        self.states["/creating_canvas"].addTransition(_creating_canvas_0)
        
        # transition /creating_clock_text
        _creating_clock_text_0 = Transition(self, self.states["/creating_clock_text"], [self.states["/creating_actual_clock_text"]])
        _creating_clock_text_0.setAction(self._creating_clock_text_0_exec)
        _creating_clock_text_0.setTrigger(Event("text_created", None))
        self.states["/creating_clock_text"].addTransition(_creating_clock_text_0)
        
        # transition /creating_actual_clock_text
        _creating_actual_clock_text_0 = Transition(self, self.states["/creating_actual_clock_text"], [self.states["/creating_interrupt_button"]])
        _creating_actual_clock_text_0.setAction(self._creating_actual_clock_text_0_exec)
        _creating_actual_clock_text_0.setTrigger(Event("text_created", None))
        self.states["/creating_actual_clock_text"].addTransition(_creating_actual_clock_text_0)
        
        # transition /creating_interrupt_button
        _creating_interrupt_button_0 = Transition(self, self.states["/creating_interrupt_button"], [self.states["/creating_resume_button"]])
        _creating_interrupt_button_0.setTrigger(Event("button_created", None))
        self.states["/creating_interrupt_button"].addTransition(_creating_interrupt_button_0)
        
        # transition /creating_resume_button
        _creating_resume_button_0 = Transition(self, self.states["/creating_resume_button"], [self.states["/running"]])
        _creating_resume_button_0.setAction(self._creating_resume_button_0_exec)
        _creating_resume_button_0.setTrigger(Event("button_created", None))
        self.states["/creating_resume_button"].addTransition(_creating_resume_button_0)
        
        # transition /running
        _running_0 = Transition(self, self.states["/running"], [self.states["/running"]])
        _running_0.setAction(self._running_0_exec)
        _running_0.setTrigger(Event("_0after"))
        self.states["/running"].addTransition(_running_0)
        _running_1 = Transition(self, self.states["/running"], [self.states["/interrupted"]])
        _running_1.setAction(self._running_1_exec)
        _running_1.setTrigger(Event("interrupt_clicked", self.getInPortName("ui")))
        self.states["/running"].addTransition(_running_1)
        
        # transition /interrupted
        _interrupted_0 = Transition(self, self.states["/interrupted"], [self.states["/interrupted"]])
        _interrupted_0.setAction(self._interrupted_0_exec)
        _interrupted_0.setTrigger(Event("interrupt_clicked", self.getInPortName("ui")))
        self.states["/interrupted"].addTransition(_interrupted_0)
        _interrupted_1 = Transition(self, self.states["/interrupted"], [self.states["/running"]])
        _interrupted_1.setAction(self._interrupted_1_exec)
        _interrupted_1.setTrigger(Event("continue_clicked", self.getInPortName("ui")))
        self.states["/interrupted"].addTransition(_interrupted_1)
    
    def _creating_window_enter(self):
        self.big_step.outputEvent(Event("create_window", self.getOutPortName("ui"), [800, 600, "Fixed Timer", self.inports['field_ui']]))
    
    def _creating_canvas_enter(self):
        self.big_step.outputEvent(Event("create_canvas", self.getOutPortName("ui"), [self.window_id, CANVAS_WIDTH, CANVAS_HEIGHT, {'background':'#222222'}, self.inports['field_ui']]))
    
    def _creating_clock_text_enter(self):
        self.big_step.outputEvent(Event("create_text", self.getOutPortName("ui"), [self.canvas_id, 50, 50, '00:00', self.inports['field_ui']]))
    
    def _creating_actual_clock_text_enter(self):
        self.big_step.outputEvent(Event("create_text", self.getOutPortName("ui"), [self.canvas_id, 50, 100, '00:00', self.inports['field_ui']]))
    
    def _creating_interrupt_button_enter(self):
        self.big_step.outputEvent(Event("create_button", self.getOutPortName("ui"), [self.window_id, 'INTERRUPT', self.inports['field_ui']]))
    
    def _creating_resume_button_enter(self):
        self.big_step.outputEvent(Event("create_button", self.getOutPortName("ui"), [self.window_id, 'RESUME', self.inports['field_ui']]))
    
    def _running_enter(self):
        self.addTimer(0, 0.05)
    
    def _running_exit(self):
        self.removeTimer(0)
    
    def _creating_window_0_exec(self, parameters):
        window_id = parameters[0]
        self.window_id = window_id
        self.big_step.outputEvent(Event("bind_event", self.getOutPortName("ui"), [window_id, ui.EVENTS.WINDOW_CLOSE, 'window_close', self.inports['field_ui']]))
        self.big_step.outputEvent(Event("bind_event", self.getOutPortName("ui"), [window_id, ui.EVENTS.KEY_PRESS, 'key_press', self.inports['field_ui']]))
    
    def _creating_canvas_0_exec(self, parameters):
        canvas_id = parameters[0]
        self.canvas_id = canvas_id
        self.big_step.outputEvent(Event("bind_event", self.getOutPortName("ui"), [canvas_id, ui.EVENTS.MOUSE_RIGHT_CLICK, 'right_click', self.inports['field_ui']]))
        self.big_step.outputEvent(Event("bind_event", self.getOutPortName("ui"), [canvas_id, ui.EVENTS.MOUSE_MOVE, 'mouse_move', self.inports['field_ui']]))
        self.big_step.outputEvent(Event("bind_event", self.getOutPortName("ui"), [canvas_id, ui.EVENTS.MOUSE_RELEASE, 'mouse_release', self.inports['field_ui']]))
    
    def _creating_clock_text_0_exec(self, parameters):
        text_id = parameters[0]
        self.clock_id = text_id
    
    def _creating_actual_clock_text_0_exec(self, parameters):
        text_id = parameters[0]
        self.actual_clock_id = text_id
    
    def _creating_resume_button_0_exec(self, parameters):
        button_id = parameters[0]
        self.button_id = button_id
        self.big_step.outputEvent(Event("bind_event", self.getOutPortName("ui"), [button_id, ui.EVENTS.MOUSE_CLICK, "mouse_click", self.inports['field_ui']]))
    
    def _running_0_exec(self, parameters):
        self.big_step.outputEvent(Event("update_text", self.getOutPortName("ui"), [self.canvas_id, self.clock_id, str('%.2f' % (self.getSimulatedTime() / 1000.0)), self.inports['field_ui']]))
        self.big_step.outputEvent(Event("update_text", self.getOutPortName("ui"), [self.canvas_id, self.actual_clock_id, str('%.2f' % (self.getSimulatedTime() / 1000.0)), self.inports['field_ui']]))
    
    def _running_1_exec(self, parameters):
        self.update_timers()
    
    def _interrupted_0_exec(self, parameters):
        self.update_timers()
    
    def _interrupted_1_exec(self, parameters):
        self.update_timers()
    
    def initializeStatechart(self):
        # enter default state
        self.default_targets = self.states["/creating_window"].getEffectiveTargetStates()
        RuntimeClassBase.initializeStatechart(self)

class MainApp(AtomicDEVS, ObjectManagerBase):
    def __init__(self, name):
        AtomicDEVS.__init__(self, name)
        ObjectManagerBase.__init__(self)
        self.elapsed = 0
        self.name = "MainApp"
        self.obj_manager_out = self.addOutPort("obj_manager_out")
        self.outputs = {}
        self.field_ui = self.addInPort("field_ui")
        self.obj_manager_in = self.addInPort("obj_manager_in")
        self.input = self.addInPort("input")
        self.instances.append(MainAppInstance(self))
        self.next_time = INFINITY
    
    def extTransition(self, inputs):
        self.simulated_time = (self.simulated_time + self.elapsed)
        self.next_time = 0
        all_inputs = []
        if self.field_ui in inputs:
            all_inputs.extend(inputs[self.field_ui])
        if self.obj_manager_in in inputs:
            all_inputs.extend(inputs[self.obj_manager_in])
        if self.input in inputs:
            all_inputs.extend(inputs[self.input])
        for input in all_inputs:
            if isinstance(input, str):
                tem = eval(input)
                self.addInput(tem)
            elif input[2].name == "create_instance":
                new_instance = MainAppInstance(self)
                self.instances.append(new_instance)
                p = new_instance.associations.get("parent")
                if p:
                    p.addInstance(input[2].instance)
                ev = Event("instance_created", None, [f"{input[2].parameters[0]}[{len(self.instances)-1}]"], input[2].instance)
                self.to_send.append((input[1], input[0], ev))
            elif input[2].name == "start_instance":
                instance = self.instances[input[2].instance]
                instance.start()
                ev = Event("instance_started", None, [f"{input[0]}[{len(self.instances)-1}]"], input[2].instance)
                self.to_send.append((input[0], input[1], ev))
            elif input[2].name == "delete_instance":
                for index in input[2].parameters[1]:
                    i = self.instances[index]
                    for assoc_name in i.associations:
                        if not (assoc_name == "parent"):
                            traversal_list = self.processAssociationReference(assoc_name)
                            instances = self.getInstances(i["instance"], traversal_list)
                            if len(instances) > 0:
                                pass
                    i.user_defined_destructor()
                    i.stop()
                self.instances = [self.instances[i] for i in range(len(self.instances)) if i not in input[2].parameters[1]]
                ev = Event("instance_deleted", None, input[2].parameters[1], input[2].instance)
                self.to_send.append((input[1], input[0], ev))
            elif input[2].name == "instance_created":
                instance = self.instances[input[2].instance]
                instance.addEvent(input[2])
            elif input[2].name == "instance_started":
                instance = self.instances[input[2].instance]
                instance.addEvent(input[2])
            elif input[2].name == "instance_deleted":
                instance = self.instances[input[2].instance]
                for association in instance.associations.items():
                    if association[1].to_class == input[0]:
                        for index in input[2].parameters:
                            association[1].removeInstance(index)
            else:
                ev = input[2]
                self.addInput(ev)
        return self.instances
    
    def intTransition(self):
        earliest = min(self.getEarliestEventTime(), self.simulated_time + self.input_queue.getEarliestTime())
        if not (earliest == INFINITY):
            self.simulated_time = earliest
        self.to_send = []
        self.handleInput()
        self.stepAll()
        next_earliest = min(self.getEarliestEventTime(), self.input_queue.getEarliestTime())
        if not (len(self.to_send) == 0):
            self.next_time = 0
        elif next_earliest == INFINITY:
            self.next_time = INFINITY
        else:
            self.next_time = next_earliest - earliest
        return self.instances
    
    def outputFnc(self):
        to_dict = {}
        for sending in self.to_send:
            if sending[2].port == None:
                if self.obj_manager_out in to_dict:
                    to_dict[self.obj_manager_out].append(sending)
                else:
                    to_dict[self.obj_manager_out] = [sending]
            else:
                the_port = None
                for port in self.OPorts:
                    if port.name == sending[0]:
                        the_port = port
                if the_port in to_dict:
                    to_dict[the_port].append(sending)
                else:
                    to_dict[the_port] = [sending]
        return to_dict
    
    def timeAdvance(self):
        return self.next_time

class ObjectManagerState:
    def __init__(self):
        self.to_send = [(None, "MainApp", Event("start_instance", None, [0], 0))]

class ObjectManager(AtomicDEVS):
    def __init__(self, name):
        AtomicDEVS.__init__(self, name)
        self.State = ObjectManagerState()
        self.input = self.addInPort("input")
        self.output = {}
        self.output["MainApp"] = self.addOutPort()
    
    def extTransition(self, inputs):
        all_inputs = inputs[self.input]
        for input in all_inputs:
            self.State.to_send.append(input)
        return self.State
    
    def intTransition(self):
        self.State.to_send = []
        return self.State
    
    def outputFnc(self):
        out_dict = {}
        for (source, target, message) in self.State.to_send:
            if self.output[target] in out_dict:
                out_dict[self.output[target]].append((source, target, message))
            else:
                out_dict[self.output[target]] = [(source, target, message)]
        return out_dict
    
    def timeAdvance(self):
        if self.State.to_send:
            return 0
        return INFINITY

class Controller(CoupledDEVS):
    def __init__(self, name):
        CoupledDEVS.__init__(self, name)
        self.ui = self.addInPort("ui")
        self.objectmanager = self.addSubModel(ObjectManager("ObjectManager"))
        self.atomic0 = self.addSubModel(MainApp("MainApp"))
        self.connectPorts(self.atomic0.obj_manager_out, self.objectmanager.input)
        self.connectPorts(self.objectmanager.output["MainApp"], self.atomic0.obj_manager_in)