"""
Generated by Statechart compiler by Glenn De Jonghe, Joeri Exelmans, Simon Van Mierlo, and Yentl Van Tendeloo (for the inspiration)

Model author: Sam Pieters
Model name:   IoTLight

"""

from sccd.runtime.statecharts_core import *

# package "IoTLight"

class Light(RuntimeClassBase):
    def __init__(self, controller):
        RuntimeClassBase.__init__(self, controller)
        
        
        self.semantics.big_step_maximality = StatechartSemantics.TakeMany
        self.semantics.internal_event_lifeline = StatechartSemantics.Queue
        self.semantics.input_event_lifeline = StatechartSemantics.FirstComboStep
        self.semantics.priority = StatechartSemantics.SourceParent
        self.semantics.concurrency = StatechartSemantics.Single
        
        # build Statechart structure
        self.build_statechart_structure()
        
        # call user defined constructor
        Light.user_defined_constructor(self)
    
    def user_defined_constructor(self):
        self.status = "#FFFFFF"
    
    def user_defined_destructor(self):
        pass
    
    
    # builds Statechart structure
    def build_statechart_structure(self):
        
        # state <root>
        self.states[""] = State(0, "", self)
        
        # state /off
        self.states["/off"] = State(1, "/off", self)
        self.states["/off"].setEnter(self._off_enter)
        
        # state /on
        self.states["/on"] = State(2, "/on", self)
        self.states["/on"].setEnter(self._on_enter)
        
        # add children
        self.states[""].addChild(self.states["/off"])
        self.states[""].addChild(self.states["/on"])
        self.states[""].fixTree()
        self.states[""].default_state = self.states["/off"]
        
        # transition /off
        _off_0 = Transition(self, self.states["/off"], [self.states["/on"]])
        _off_0.setTrigger(Event("button_pressed", None))
        self.states["/off"].addTransition(_off_0)
    
    def _off_enter(self):
        self.status = "#000000"
        print(self.status)
    
    def _on_enter(self):
        self.status = "#FFFFFF"
        print(self.status)
    
    def initializeStatechart(self):
        # enter default state
        self.default_targets = self.states["/off"].getEffectiveTargetStates()
        RuntimeClassBase.initializeStatechart(self)

class ColorLight(Light):
    def __init__(self, controller):
        RuntimeClassBase.__init__(self, controller)
        
        
        self.semantics.big_step_maximality = StatechartSemantics.TakeMany
        self.semantics.internal_event_lifeline = StatechartSemantics.Queue
        self.semantics.input_event_lifeline = StatechartSemantics.FirstComboStep
        self.semantics.priority = StatechartSemantics.SourceParent
        self.semantics.concurrency = StatechartSemantics.Single
        
        # build Statechart structure
        self.build_statechart_structure()
        
        # call user defined constructor
        ColorLight.user_defined_constructor(self)
    
    def user_defined_constructor(self):
        Light.user_defined_constructor(self)
    
    def user_defined_destructor(self):
        # call super class destructors
        Light.user_defined_destructor(self)
    
    
    # builds Statechart structure
    def build_statechart_structure(self):
        
        # state <root>
        self.states[""] = State(0, "", self)
        
        # state /off
        self.states["/off"] = State(1, "/off", self)
        self.states["/off"].setEnter(self._off_enter)
        
        # state /on
        self.states["/on"] = State(2, "/on", self)
        self.states["/on"].setEnter(self._on_enter)
        
        # add children
        self.states[""].addChild(self.states["/off"])
        self.states[""].addChild(self.states["/on"])
        self.states[""].fixTree()
        self.states[""].default_state = self.states["/off"]
        
        # transition /off
        _off_0 = Transition(self, self.states["/off"], [self.states["/on"]])
        _off_0.setTrigger(Event("button_pressed", None))
        self.states["/off"].addTransition(_off_0)
    
    def _off_enter(self):
        self.status = "#000000"
        print(self.status)
    
    def _on_enter(self):
        self.status = "#00FF00"
        print(self.status)
    
    def initializeStatechart(self):
        # enter default state
        self.default_targets = self.states["/off"].getEffectiveTargetStates()
        RuntimeClassBase.initializeStatechart(self)

class ObjectManager(ObjectManagerBase):
    def __init__(self, controller):
        ObjectManagerBase.__init__(self, controller)
    
    def instantiate(self, class_name, construct_params):
        if class_name == "Light":
            instance = Light(self.controller)
            instance.associations = {}
        elif class_name == "ColorLight":
            instance = ColorLight(self.controller)
            instance.associations = {}
        else:
            raise Exception("Cannot instantiate class " + class_name)
        return instance

class Controller(ThreadsControllerBase):
    def __init__(self, keep_running = None, behind_schedule_callback = None):
        if keep_running == None: keep_running = True
        if behind_schedule_callback == None: behind_schedule_callback = None
        ThreadsControllerBase.__init__(self, ObjectManager(self), keep_running, behind_schedule_callback)
        self.addInputPort("Input")
        self.addOutputPort("Outport")
        self.object_manager.createInstance("ColorLight", [])